# Generated by Django 4.2.1 on 2023-06-22 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('region', models.CharField(max_length=60, verbose_name='Область')),
                ('reception_lap', models.BooleanField(default=False, verbose_name='Прием')),
                ('delivery_lap', models.BooleanField(default=False, verbose_name='Выдача')),
                ('code', models.CharField(max_length=50, verbose_name='Код Боксберри')),
                ('courier_delivery', models.BooleanField(default=False, verbose_name='Курьерская доставка')),
                ('kladr', models.CharField(max_length=55, verbose_name='Кладр')),
                ('dpd_code', models.CharField(max_length=55, null=True, verbose_name='Код ДПД')),
                ('bxb_point_code', models.CharField(max_length=55, null=True, verbose_name='Код ПВЗ ББ')),
                ('cdek_code', models.IntegerField(null=True, verbose_name='Код СДЭК')),
                ('cdek_uuid', models.UUIDField(null=True, verbose_name='UUID СДЭК')),
                ('country_code', models.CharField(default=643, max_length=5, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DeliveryServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True, verbose_name='Код')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='Название')),
                ('height', models.IntegerField(null=True, verbose_name='Высота')),
                ('depth', models.IntegerField(null=True, verbose_name='Длина')),
                ('width', models.IntegerField(null=True, verbose_name='Ширина')),
                ('weight', models.FloatField(null=True, verbose_name='Вес')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('code', models.IntegerField(verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Тип доставки',
                'verbose_name_plural': 'Типы доставки',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Длина')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('dpd_shop_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название короба в DPD Shop')),
                ('pony_express_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название короба в PonyExpress')),
                ('cdek_box_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Название короба в CDEK Посылочка')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Объем')),
                ('pip', models.BooleanField(default=True, verbose_name='ПиП')),
                ('in_report', models.BooleanField(default=True, verbose_name='В отчете ПиП')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название типа')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Код тарифной зоны')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField(verbose_name='Индекс')),
                ('in_calc', models.BooleanField(default=True, verbose_name='Учавствует в рассчете')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zips', to='location.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Индекс',
                'verbose_name_plural': 'Индексы',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(null=True)),
                ('receiver_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_cities', to='location.city', verbose_name='Город получатель')),
                ('sender_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_cities', to='location.city', verbose_name='Город отправитель')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='location.zone', verbose_name='Зона')),
                ('zone_avito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_avito', to='location.zone', verbose_name='Зона Авито')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=12, verbose_name='Код')),
                ('address', models.CharField(max_length=200, verbose_name='Адресс')),
                ('courier', models.CharField(max_length=50, null=True, verbose_name='Партнер')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('kladr', models.CharField(max_length=25, null=True, verbose_name='КЛАДР')),
                ('reception_lap', models.BooleanField(default=False, verbose_name='Прием')),
                ('delivery_lap', models.BooleanField(default=False, verbose_name='Выдача')),
                ('active', models.BooleanField(default=True, verbose_name='Действующая')),
                ('zip', models.IntegerField(null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='location.city')),
            ],
            options={
                'verbose_name': 'Пункт выдачи',
                'verbose_name_plural': 'Пункты выдачи',
            },
        ),
    ]
