# Generated by Django 4.2.1 on 2023-06-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='delivery_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.service', verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='point',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.pointtype', verbose_name='Тип отделения'),
        ),
        migrations.AddField(
            model_name='package',
            name='sberlogistic_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.deliveryservicepackage', verbose_name='Короб Сберлогистики'),
        ),
        migrations.AddField(
            model_name='deliveryservicepackage',
            name='delivery_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.deliverytariff', verbose_name='Тариф'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['code'], name='location_ci_code_2b4205_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['country_code'], name='location_ci_country_b55d17_idx'),
        ),
        migrations.AddIndex(
            model_name='zip',
            index=models.Index(fields=['zip'], name='location_zi_zip_648828_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['sender_city', 'receiver_city'], name='location_ro_sender__94bd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['code'], name='location_po_code_6b6a4e_idx'),
        ),
    ]
