# Generated by Django 3.2.18 on 2023-06-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryservicepackage',
            options={'ordering': ['weight'], 'verbose_name': 'Кастомные параметры упаковки', 'verbose_name_plural': 'Кастомные параметры упаковок'},
        ),
    ]
