# Generated by Django 4.2.1 on 2023-06-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_deliveryservicepackage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='receiver_city',
            field=models.ForeignKey(limit_choices_to={'country_code': 643, 'delivery_lap': True}, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_cities', to='location.city', verbose_name='Город получатель'),
        ),
        migrations.AlterField(
            model_name='route',
            name='sender_city',
            field=models.ForeignKey(limit_choices_to={'country_code': 643, 'delivery_lap': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sender_cities', to='location.city', verbose_name='Город отправитель'),
        ),
        migrations.AlterField(
            model_name='route',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='zone_avito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_avito', to='location.zone', verbose_name='Зона Авито'),
        ),
    ]
