# Generated by Django 4.2.1 on 2023-07-06 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_route_receiver_city_alter_route_sender_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='cdek_box_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdek_box_package', to='location.deliveryservicepackage', verbose_name='Короб СДЭК Посылочки'),
        ),
    ]
