# Generated by Django 4.2.1 on 2023-06-22 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
        ('tariff_guide', '0001_initial'),
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytariff',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.direction', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='deliverytariff',
            name='packages',
            field=models.ManyToManyField(to='location.package', verbose_name='Упаковки для парсинга'),
        ),
        migrations.AddField(
            model_name='deliverytariff',
            name='parsing_groups',
            field=models.ManyToManyField(to='tariff_guide.parsinggroup', verbose_name='Группы парсинга'),
        ),
        migrations.AddField(
            model_name='deliverytariff',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.deliverytype', verbose_name='Тип Доставки'),
        ),
    ]
