# Generated by Django 3.2.18 on 2023-06-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_guide', '0004_parsingmodels'),
        ('parser', '0004_alter_deliverytariff_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytariff',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.apicodes', verbose_name='Код тарифа'),
        ),
    ]
