# Generated by Django 4.2.1 on 2023-06-22 20:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tariff_guide.managers.price
import tariff_guide.managers.time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parser', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField(verbose_name='Максимальный срок')),
                ('min', models.IntegerField(verbose_name='Минимальный срок')),
                ('cheaper', models.ManyToManyField(related_name='time_cheaper', to='parser.deliverytariff')),
                ('more_expensive', models.ManyToManyField(related_name='time_more_expensive', to='parser.deliverytariff')),
            ],
            options={
                'verbose_name': 'Срок',
                'verbose_name_plural': 'Сроки',
            },
            bases=(models.Model, tariff_guide.managers.time.DeliveryTimeManager),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, verbose_name='Направление (ПиП/ИМ)')),
                ('code', models.IntegerField(default=1, verbose_name='Код направления')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='ParsingTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('is_fast', models.BooleanField(default=False, verbose_name='Самый быстрый')),
                ('is_slowest', models.BooleanField(default=False, verbose_name='Самый медленный')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.route', verbose_name='Маршрут')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_tariffs', to='parser.deliverytariff', verbose_name='Тариф')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.deliverytime', verbose_name='Сроки доставки')),
            ],
            options={
                'verbose_name': 'Тариф на маршрут',
                'verbose_name_plural': 'Тарифы на маршрут',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.IntegerField(null=True, verbose_name='Код')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание сценария')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
            },
        ),
        migrations.CreateModel(
            name='ServiceCustomPackageName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('in_report', models.BooleanField(default=True, verbose_name='Отображать в отчете')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.package', verbose_name='Упаковка')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.deliverytariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Кастомное название упаковки',
                'verbose_name_plural': 'Кастомные названия упаковок',
                'ordering': ['package__weight'],
            },
        ),
        migrations.CreateModel(
            name='ParsingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('top_count', models.IntegerField(default=0, verbose_name='Кол-во ТОП маршрутов')),
                ('public', models.BooleanField(default=True, verbose_name='Публичная группа')),
                ('subscriber', models.URLField(null=True, verbose_name='Подписка на изменение')),
                ('in_report', models.BooleanField(default=True, verbose_name='Отображается в отчете')),
                ('city', models.ManyToManyField(to='location.city', verbose_name='Город')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.direction', verbose_name='Направление')),
                ('routes', models.ManyToManyField(to='location.route', verbose_name='Список маршрутов')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.script', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Группа парсинга',
                'verbose_name_plural': 'Группы парсинга',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='Код тарифа')),
                ('tittle', models.CharField(max_length=45, verbose_name='Название тарифа')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tariff_guide.direction', verbose_name='Направление')),
                ('serviсe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.service', verbose_name='Служба доставки')),
            ],
            options={
                'verbose_name': 'Код тарифа служб доставок',
                'verbose_name_plural': 'Коды тарифов служб доставок',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('is_min', models.BooleanField(default=False, verbose_name='Минимальный на маршруте')),
                ('is_max', models.BooleanField(default=False, verbose_name='Минимальный на маршруте')),
                ('cheaper', models.ManyToManyField(related_name='price_cheaper', to='parser.deliverytariff')),
                ('more_expensive', models.ManyToManyField(related_name='price_more_expensive', to='parser.deliverytariff')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.package', verbose_name='Короб')),
                ('tariffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='tariff_guide.parsingtariff', verbose_name='Тарифф')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'indexes': [models.Index(fields=['package', 'tariffs'], name='tariff_guid_package_f606d5_idx'), models.Index(fields=['is_min'], name='tariff_guid_is_min_685571_idx'), models.Index(fields=['is_max'], name='tariff_guid_is_max_809ddf_idx')],
            },
            bases=(models.Model, tariff_guide.managers.price.PriceManager),
        ),
        migrations.AddIndex(
            model_name='parsingtariff',
            index=models.Index(fields=['route', 'tariff'], name='tariff_guid_route_i_72bec2_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtariff',
            index=models.Index(fields=['is_fast'], name='tariff_guid_is_fast_35793e_idx'),
        ),
        migrations.AddIndex(
            model_name='parsingtariff',
            index=models.Index(fields=['is_slowest'], name='tariff_guid_is_slow_114130_idx'),
        ),
    ]
