# Generated by Django 3.2.18 on 2023-06-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_initial'),
        ('tariff_guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['package__weight'], 'verbose_name': 'Цена', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterField(
            model_name='price',
            name='cheaper',
            field=models.ManyToManyField(related_name='price_cheaper', to='parser.DeliveryTariff', verbose_name='Дешевле чем'),
        ),
        migrations.AlterField(
            model_name='price',
            name='more_expensive',
            field=models.ManyToManyField(related_name='price_more_expensive', to='parser.DeliveryTariff', verbose_name='Дороже чем'),
        ),
    ]
