# Generated by Django 4.2.1 on 2023-06-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff_guide', '0003_alter_parsinggroup_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=45, verbose_name='Код Модели')),
            ],
            options={
                'verbose_name': 'Модель для парсинга',
                'verbose_name_plural': 'Модели для парсинга',
            },
        ),
    ]
