# Generated by Django 4.2.1 on 2023-07-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_alter_deliverytariff_code'),
        ('tariff_guide', '0004_parsingmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cheaper',
            field=models.ManyToManyField(blank=True, related_name='price_cheaper', to='parser.deliverytariff', verbose_name='Дешевле чем'),
        ),
        migrations.AlterField(
            model_name='price',
            name='more_expensive',
            field=models.ManyToManyField(blank=True, related_name='price_more_expensive', to='parser.deliverytariff', verbose_name='Дороже чем'),
        ),
    ]
